/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;


import java.awt.EventQueue;
import javax.swing.JOptionPane;
import modele.Admin;
import modele.Connection_DB;
import java.awt.event.WindowAdapter;
import controller.AdminController;
import view.AccueilAdmin;









/**
 *
 * @author tango
 */
public class LoginAdmin extends javax.swing.JFrame {
    private AdminController controller;
    
    
    
    

    /** Creates new form LoginAdmin */
    public LoginAdmin() {
        controller = new AdminController(); // Initialisation du contrôleur
      
        initComponents();
 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jadmin = new javax.swing.JTextField();
        LoginAdmin = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Email :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mot de Passe :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(163, 130, 97));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 110, 30));
        jPanel1.add(jadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 88, 140, -1));

        LoginAdmin.setBackground(new java.awt.Color(163, 130, 97));
        LoginAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginAdmin.setText("Se Connecter");
        LoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginAdminActionPerformed(evt);
            }
        });
        jPanel1.add(LoginAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 110, 30));
        jPanel1.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 140, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ffff.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginAdminActionPerformed
         
        try{ 
     
     String emailText=jadmin.getText().trim();
     String password =new String(jpassword.getText());
     
     if(emailText.isEmpty()|| password.isEmpty()){
         JOptionPane.showMessageDialog(this, "Email et mot de passe sont obligatoires","Erreur",JOptionPane.WARNING_MESSAGE);
         return;
         }
     
              // 2. Validation du format de l'email pour les administrateurs
         if (!jadmin.getText().endsWith("@admin.adoption.com")) {
        JOptionPane.showMessageDialog(this, "Veuillez entrer un email valide", 
        "Erreur", JOptionPane.ERROR_MESSAGE);
    return;
}
         Admin admin =controller.LoginAdmin(emailText, password);
         if(admin !=null){
             JOptionPane.showMessageDialog(this,"Connexion réussie ! Bienvenue"+admin.getNom(),"Succès",JOptionPane.INFORMATION_MESSAGE);
              
    
             
            this.dispose(); // Ferme la fenêtre de login
            
            /*EventQueue.invokeLater(() -> {
                AccueilAdmin accueil = new AccueilAdmin(admin);
                accueil.setVisible(true);
                accueil.setLocationRelativeTo(null); // Centre la fenêtre
            });*/
         }
         else{
             JOptionPane.showMessageDialog(this, "Emai ou mot de passe incorrect","Erreur",JOptionPane.ERROR_MESSAGE);
         }
       
     }
     catch(Exception e){
             JOptionPane.showMessageDialog(this, "Erreur technique:"+e.getMessage(),"Erreur Critique",JOptionPane.ERROR_MESSAGE);
             e.printStackTrace();
             }
        
        AccueilAdmin acc =new AccueilAdmin();
        acc.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_LoginAdminActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          this.dispose(); // Fermer la fenêtre
            
                                   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jadmin;
    private javax.swing.JPasswordField jpassword;
    // End of variables declaration//GEN-END:variables

}
