/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AnimalController;
import controller.ClientController;
import controller.AdminController;
import modele.Connection_DB;
import javax.swing.JOptionPane;
import modele.Animal;
import modele.Client;
import modele.Admin;


/**
 *
 * @author tango
 */
public class ViewAjouter extends javax.swing.JFrame {
     private AnimalController controller;
    /**
     * Creates new form ViewAjouter
     */
    public ViewAjouter() {
         controller = new AnimalController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        poids = new javax.swing.JTextField();
        taille = new javax.swing.JTextField();
        prix = new javax.swing.JTextField();
        sexe = new javax.swing.JTextField();
        statut = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setText("Nom :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 87, 37, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setText("Age :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 128, 37, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setText("Poids :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 169, 37, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setText("Taille :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 210, 37, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setText("Prix :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 251, 37, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setText("Sexe :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 292, 37, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel8.setText("Statut :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 333, 54, -1));
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 83, 104, -1));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 124, 104, -1));
        jPanel1.add(poids, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 165, 104, -1));
        jPanel1.add(taille, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 206, 104, -1));
        jPanel1.add(prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 247, 104, -1));
        jPanel1.add(sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 288, 104, -1));
        jPanel1.add(statut, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 329, 104, -1));

        jButton1.setBackground(new java.awt.Color(163, 130, 97));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 369, 90, -1));

        jButton2.setBackground(new java.awt.Color(163, 130, 97));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Fermer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 369, 90, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ffff.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel10.setText("Nom :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 87, 37, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose(); // Fermer la fenêtre
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Validation des champs
        if (nom.getText().isEmpty() || 
            age.getText().isEmpty() || poids.getText().isEmpty() || taille.getText().isEmpty() ||
            prix.getText().isEmpty() || sexe.getText().isEmpty() 
            || statut.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Tous les champs obligatoires doivent être remplis", 
            "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
// 3. Création d'un animal
         
        Animal nouveauAnimal = new Animal();
      
        nouveauAnimal.setNom(nom.getText());
        nouveauAnimal.setAge(age.getText());
        nouveauAnimal.setPoids(poids.getText());
        nouveauAnimal.setTaille(taille.getText());
        nouveauAnimal.setPrix(prix.getText());
        nouveauAnimal.setSexe(sexe.getText());
        nouveauAnimal.setStatut(statut.getText());
        
        
      
        
        
          
       
        // 4. Appel au contrôleur
        boolean resultat = controller.ajouterAnimal(nouveauAnimal);
        
        if (resultat) {
            JOptionPane.showMessageDialog(this, "L'animal a été ajouté avec succès!", 
                "Succès", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Fermer la fenêtre d'inscription
        } else {
            JOptionPane.showMessageDialog(this, "Échec ", 
                "Erreur", JOptionPane.ERROR_MESSAGE);
        }   
       
   
        
                                            

    /**
     * @param args the command line arguments
     */
 




        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField poids;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField sexe;
    private javax.swing.JTextField statut;
    private javax.swing.JTextField taille;
    // End of variables declaration//GEN-END:variables
}
                       

        
    
        
    

            

