/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ClientController;
import modele.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author tango
 */
public class ViewInsciption extends javax.swing.JFrame {
    
private ClientController controller;
    /**
     * Creates new form ViewInsciption
     */
    public ViewInsciption() {
        initComponents();
        controller = new ClientController();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ajouterClient = new javax.swing.JButton();
        mot_de_passe = new javax.swing.JPasswordField();
        conf_mdp = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setText("Nom :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 50, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setText("Confirmer Mot de passe :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setText("Prénom :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setText("Email :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setText("Téléphone :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setText("Mot de passe :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 140, -1));

        prenom.setText(" ");
        jPanel1.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 140, -1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 140, -1));

        telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneActionPerformed(evt);
            }
        });
        jPanel1.add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 140, -1));

        jButton1.setBackground(new java.awt.Color(163, 130, 97));
        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 110, 30));

        ajouterClient.setBackground(new java.awt.Color(163, 130, 97));
        ajouterClient.setText("S'inscrire");
        ajouterClient.setMaximumSize(new java.awt.Dimension(72, 23));
        ajouterClient.setMinimumSize(new java.awt.Dimension(72, 23));
        ajouterClient.setPreferredSize(new java.awt.Dimension(72, 23));
        ajouterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterClientActionPerformed(evt);
            }
        });
        jPanel1.add(ajouterClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 100, 30));
        jPanel1.add(mot_de_passe, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 140, -1));
        jPanel1.add(conf_mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 140, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ffff.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneActionPerformed

    }//GEN-LAST:event_telephoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); // Fermer la fenêtre

      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ajouterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterClientActionPerformed
        // 1. Validation des champs
        if (nom.getText().isEmpty() || prenom.getText().isEmpty() || 
            email.getText().isEmpty() || mot_de_passe.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tous les champs obligatoires doivent être remplis", 
                "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
          // Validation du format  du nom 
          if(!nom.getText().matches("[a-z A-Z]+")){
              JOptionPane.showMessageDialog(this, "Veuillez entrer dans le champ nom uniquement des lettres (a-z A-Z)" , "Erreur de format", JOptionPane.ERROR_MESSAGE);
              return;
          }
          
          // Validation du format du prenom 
           if(!prenom.getText().matches("[a-z A-Z]+")){
              JOptionPane.showMessageDialog(this, "Veuillez entrer dans le champ prenom uniquement des lettres (a-z A-Z)" , "Erreur de format", JOptionPane.ERROR_MESSAGE);
              return;
          }
          
          
       
             
        
        // 2. Vérification de la confirmation du mot de passe
        if (!mot_de_passe.getText().equals(conf_mdp.getText())) {
            JOptionPane.showMessageDialog(this, "Les mots de passe ne correspondent pas", 
                "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Création du client
        Client nouveauClient = new Client();
        nouveauClient.setNom(nom.getText());
        nouveauClient.setPrenom(prenom.getText());
        nouveauClient.setEmail(email.getText());
        nouveauClient.setMot_de_passe(mot_de_passe.getText());
        
        try {
            nouveauClient.setTelephone(Integer.parseInt(telephone.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Le téléphone doit être un nombre", 
                "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
          
        
        
        nouveauClient.setVille(""); // Adaptez si vous avez un champ ville

        // 4. Appel au contrôleur
        boolean resultat = controller.ajouterClient(nouveauClient);
        
        if (resultat) {
            JOptionPane.showMessageDialog(this, "Inscription réussie !", 
                "Succès", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Fermer la fenêtre d'inscription
        } else {
            JOptionPane.showMessageDialog(this, "Échec de l'inscription. L'email existe peut-être déjà.", 
                "Erreur", JOptionPane.ERROR_MESSAGE);
        }    
        ViewLogin accueil=new ViewLogin();
        accueil.setVisible(true);

      
       
        
        
    }//GEN-LAST:event_ajouterClientActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInsciption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInsciption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInsciption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInsciption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInsciption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterClient;
    private javax.swing.JPasswordField conf_mdp;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField mot_de_passe;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables
}
