/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.EventQueue;
import javax.swing.JOptionPane;
import modele.Client;
import modele.Animal;
import view.ViewLabrador;
import view.ViewBerger;
import view.ViewHusky;
import view.ViewBouledogue;
import view.ViewMaine;
import view.ViewSiamois;
import view.ViewAbssyn;
import view.ViewBengal;
/**
 *
 * @author tango
 */
public class ViewAccueil extends javax.swing.JFrame {
  private Client client ;
  private Animal animal;
    /**
     * Creates new form ViewAccueil
     */
    public ViewAccueil(Client client) {
        this.client=client;
       
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        berger = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labrador = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        husky = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bouledogue = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        maine = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        siamois = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        abyssin = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        bengal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jButton1.setText("Berger Allemand");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Catalogue des animaux");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 6, 236, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/berger111.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 49, -1, -1));

        berger.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        berger.setText("Berger Allemand");
        berger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bergerActionPerformed(evt);
            }
        });
        jPanel1.add(berger, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 155, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/slll.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 49, -1, -1));

        labrador.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        labrador.setText("Labrador Retriever");
        labrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labradorActionPerformed(evt);
            }
        });
        jPanel1.add(labrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 155, 100, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/huuu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 49, -1, -1));

        husky.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        husky.setText("Husky Sibérien");
        husky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huskyActionPerformed(evt);
            }
        });
        jPanel1.add(husky, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 155, 100, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Bouledogue Français.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 49, -1, -1));

        bouledogue.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        bouledogue.setText("Bouledogue Français ");
        bouledogue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouledogueActionPerformed(evt);
            }
        });
        jPanel1.add(bouledogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 155, 100, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/maineCoon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 249, -1, -1));

        maine.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        maine.setText("Maine Coon ");
        maine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maineActionPerformed(evt);
            }
        });
        jPanel1.add(maine, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 367, 100, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/cha11.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 249, -1, -1));

        siamois.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        siamois.setText("Siamois");
        siamois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siamoisActionPerformed(evt);
            }
        });
        jPanel1.add(siamois, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 367, 100, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Abyssin11.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 249, -1, -1));

        abyssin.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        abyssin.setText("Abyssin");
        abyssin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abyssinActionPerformed(evt);
            }
        });
        jPanel1.add(abyssin, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 367, 100, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Bengal111.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 249, -1, -1));

        bengal.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        bengal.setText("Bengal");
        bengal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bengalActionPerformed(evt);
            }
        });
        jPanel1.add(bengal, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 367, 100, -1));

        jButton2.setText("jButton2");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 160, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ffff.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bergerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bergerActionPerformed
       
    
     try{
                ViewBerger bergerView = new ViewBerger(animal);
                bergerView.setVisible(true);
                this.dispose();}
     catch(Exception ex){
         JOptionPane.showMessageDialog(this, "error "+ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
     }
               
    }//GEN-LAST:event_bergerActionPerformed

    private void labradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labradorActionPerformed
       
    
    try{
                ViewLabrador labradorView = new  ViewLabrador (animal);
                labradorView.setVisible(true);
                this.dispose();}
     catch(Exception ex){
         JOptionPane.showMessageDialog(this, "error "+ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
     }
    }//GEN-LAST:event_labradorActionPerformed

    private void huskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huskyActionPerformed
        try{
                ViewHusky huskyView = new  ViewHusky (animal);
                huskyView.setVisible(true);
                this.dispose();}
     catch(Exception ex){
         JOptionPane.showMessageDialog(this, "error "+ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
     }
    }//GEN-LAST:event_huskyActionPerformed

    private void bouledogueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouledogueActionPerformed
          try{
                ViewBouledogue bouledogueView = new ViewBouledogue(animal);
                bouledogueView.setVisible(true);
                this.dispose();}
     catch(Exception ex){
         JOptionPane.showMessageDialog(this, "error "+ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
     }
    }//GEN-LAST:event_bouledogueActionPerformed

    private void maineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maineActionPerformed
        try{
                ViewMaine maineView = new ViewMaine(animal);
                maineView.setVisible(true);
                this.dispose();}
        catch(Exception ex){
         JOptionPane.showMessageDialog(this, "error "+ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
     }
    }//GEN-LAST:event_maineActionPerformed

    private void siamoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siamoisActionPerformed
         try{
                ViewSiamois siamoisView = new ViewSiamois(animal);
                siamoisView.setVisible(true);
                this.dispose();}
     catch(Exception ex){
         JOptionPane.showMessageDialog(this, "error "+ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
     }
    }//GEN-LAST:event_siamoisActionPerformed

    private void abyssinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abyssinActionPerformed
          try{
                ViewAbssyn abssynView = new ViewAbssyn(animal);
                abssynView.setVisible(true);
                this.dispose();}
     catch(Exception ex){
         JOptionPane.showMessageDialog(this, "error "+ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
     }
    }//GEN-LAST:event_abyssinActionPerformed

    private void bengalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bengalActionPerformed
          try{
                ViewBengal bengalView = new ViewBengal(animal);
                bengalView.setVisible(true);
                this.dispose();}
     catch(Exception ex){
         JOptionPane.showMessageDialog(this, "error "+ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
     }
    }//GEN-LAST:event_bengalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abyssin;
    private javax.swing.JButton bengal;
    private javax.swing.JButton berger;
    private javax.swing.JButton bouledogue;
    private javax.swing.JButton husky;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton labrador;
    private javax.swing.JButton maine;
    private javax.swing.JButton siamois;
    // End of variables declaration//GEN-END:variables
}
